// Presentation copy only; server capability gates remain authoritative.
export const pilotCopy = {
  de: {
    merchantStart: 'Händlerkonto anlegen', merchantLogin: 'Händler-Login',
    merchantTitle: 'Dein Geschäft. Deine Produkte. Dein Verkaufsschild.',
    merchantIntro: 'Pflege Produkte, Preise und Verfügbarkeit im Händlerportal. Die Schilderbereitstellung stimmen wir im Pilot gemeinsam ab.',
    merchantScope: 'Ein realer Händler, zwei echte Schilder: Reservierung, Notify und Stripe-Testkauf sind abgenommen.',
    commerceScope: 'Käufe ausschließlich im Stripe-Testmodus. Keine Abbuchung; Live-Zahlungen und Auszahlungen sind noch nicht freigegeben.',
    hero: 'Dein Schaufenster verkauft weiter – auch wenn du längst geschlossen hast.',
    heroText: 'Kunden scannen das Produkt direkt im Schaufenster und kaufen oder reservieren sofort am Smartphone – ohne App und ohne Personal vor Ort.',
    heroTrust: 'Funktionierender MVP · sichere Demo im Stripe-Testmodus · Pilotphase',
    heroPoints: ['Keine App', 'Sicher bezahlen', 'Schild reagiert live'],
    demoCta: 'Live erleben', pilotCta: 'Pilotpartner werden', talk: 'Pilotpartner werden',
    quickSteps: [['SEHEN', 'Produkt im Schaufenster sehen'], ['SCANNEN', 'QR scannen – keine App nötig'], ['KAUFEN', 'Direkt kaufen oder reservieren']],
    quickNote: 'Das physische Schild aktualisiert sich automatisch.',
    demoTitle: 'Sehen. Scannen. Kaufen. Das Schild reagiert.',
    demoText: 'Produkt auswählen, QR scannen, am Smartphone kaufen oder reservieren.',
    demoIntroHardware: 'Hier siehst du eine Simulation des Verkaufsschilds.',
    demoIntroHardwareDetail: 'Auch mit zwei echten Merchant-Schildern abgenommen. Diese öffentliche Demo ist nicht mit ihnen gekoppelt.',
    demoSteps: ['Produkt auswählen', 'QR scannen', 'Kaufen oder reservieren', 'Display reagiert'],
    demoSafetyLabel: 'Sichere Demo', demoSafetyText: 'Stripe-Testmodus · keine Abbuchung · keine echte Bestellung',
    demoSafetyGuide: 'Testkarte: 4242 4242 4242 4242', demoSafetyConfirm: 'Demo starten',
    demoSafetyWaiting: 'Bestätige den Testmodus, um die Demo zu starten.',
    problemTitle: 'Samstagabend. Dein Produkt gefällt. Die Tür ist zu.',
    today: 'HEUTE', withQr2buy: 'MIT QR2BUY',
    problemBefore: ['Produkt gefällt.', 'Geschäft geschlossen.', 'Kunde geht weiter.'],
    problemAfter: ['QR scannen.', 'Bezahlen oder reservieren.', 'Verkauft oder reserviert.'],
    benefitsTitle: 'Aus Interesse wird ein Kaufmoment.', benefitsText: 'Direkt beim sichtbaren Produkt.',
    benefits: [['Keine App', 'Kamera öffnen und loslegen.'], ['Auch nach Ladenschluss', 'Kaufen oder reservieren, wenn das Produkt gefällt.'], ['Sichtbare Rückmeldung', 'Das Schild zeigt den bestätigten Vorgang.']],
    compareQr2buyText: 'Genau dieses Produkt. Preis und Verfügbarkeit. Kaufen oder reservieren.',
    compareStandardItems: ['Führt zu einer Website', 'Kennt das konkrete Produkt nicht automatisch', 'Schild bleibt statisch'],
    compareQr2buyItems: ['Führt zu genau diesem Produkt', 'Zeigt Preis und Verfügbarkeit', 'Kauf oder Reservierung am Smartphone', 'Schild reagiert auf den bestätigten Vorgang'],
    trustTitle: 'Du weißt, was du kaufst.', trustText: 'Produkt, Preis und bestätigte Rückmeldung auf Smartphone und Schild.',
    trustItems: ['Genau das Produkt vor dir', 'Preis und Verfügbarkeit vor dem Kauf', 'Zahlung über Stripe – aktuell nur Testmodus', 'Kaufbestätigung per Mail im abgenommenen Merchant-Testkauf'],
    cases: [['Boutique', 'Lieblingsstücke im Schaufenster.'], ['Galerie', 'Kunst direkt vor Augen.'], ['Showroom', 'Ausgestellte Produkte entdecken.'], ['Saisonaler Verkaufsstand', 'Sichtbare Produkte, auch ohne Personal vor Ort.']],
    casesText: 'Und überall dort, wo Produkte sichtbar sind, obwohl gerade niemand verkauft.',
    howSteps: [['1', 'Produkt sehen', 'Name, Preis und QR direkt am Produkt.'], ['2', 'QR scannen', 'Kamera und Browser reichen.'], ['3', 'Kaufen oder reservieren', 'Das Schild zeigt den bestätigten Vorgang.']],
    hardwareTitle: 'Ein Preisschild, das verkaufen kann.',
    hardwareText: 'Zwei echte Displays sind im MVP abgenommen. Funktionsfähige Prototypen; Gehäuse und finales Produktdesign folgen im Pilot.',
    hardwareFacts: ['Produkt', 'Preis', 'QR und Verfügbarkeit', 'Live-Reaktion', 'Wiederverwendbar'],
    pilotTitle: 'QR2BUY im eigenen Schaufenster testen.', pilotText: 'Wir planen einen überschaubaren Pilot mit deinen sichtbaren Produkten.',
    faq: [['Kann ich mich als Händler registrieren?', 'Ja. Das Händlerportal ist verfügbar. Schilderbereitstellung und Pilotumfang stimmen wir gemeinsam ab.'], ['Kann ich echte Zahlungen empfangen?', 'Noch nicht. Der Merchant-Kauf ist im Stripe-Testmodus abgenommen; Live-Zahlungen und Auszahlungen sind nicht freigegeben.'], ['Ist die Demo eine echte Bestellung?', 'Nein. Nur Testdaten und Stripe-Testmodus, keine Abbuchung und keine echte Bestellung.'], ['Gibt es echte Schilder?', 'Ja. Zwei physische Prototypen sind mit einem realen Händler abgenommen.'], ['Brauchen Kunden eine App?', 'Nein. Kamera und Browser reichen.'], ['Was kostet der Pilot?', 'Umfang und Preis planen wir gemeinsam.']],
  },
  en: {
    merchantStart: 'Create merchant account', merchantLogin: 'Merchant login',
    merchantTitle: 'Your shop. Your products. Your sales display.',
    merchantIntro: 'Manage products, prices and availability in the merchant portal. We arrange displays together within the pilot.',
    merchantScope: 'One real merchant, two real displays: reservations, notifications and a Stripe test purchase have passed acceptance.',
    commerceScope: 'Stripe test mode only. No charges; live payments and payouts are not yet enabled.',
    hero: 'Your shop window keeps selling – long after you have closed.',
    heroText: 'Customers scan the product in your window and buy or reserve on their phone – no app and no staff on site.',
    heroTrust: 'Working MVP · safe demo in Stripe test mode · Pilot phase',
    heroPoints: ['No app', 'Secure payment', 'Display reacts live'],
    demoCta: 'Experience it live', pilotCta: 'Become a pilot partner', talk: 'Become a pilot partner',
    quickSteps: [['SEE', 'Spot the product in the window'], ['SCAN', 'Scan the QR – no app needed'], ['BUY', 'Buy or reserve directly']],
    quickNote: 'The physical display updates automatically.',
    demoTitle: 'See. Scan. Buy. Watch the display react.',
    demoText: 'Choose a product, scan the QR, buy or reserve on your phone.',
    demoIntroHardware: 'This is a simulation of the sales display.',
    demoIntroHardwareDetail: 'Also accepted on two real merchant displays. This public demo is not paired with them.',
    demoSteps: ['Choose a product', 'Scan the QR', 'Buy or reserve', 'Display reacts'],
    demoSafetyLabel: 'Safe demo', demoSafetyText: 'Stripe test mode · no charge · no real order',
    demoSafetyGuide: 'Test card: 4242 4242 4242 4242', demoSafetyConfirm: 'Start demo',
    demoSafetyWaiting: 'Confirm test mode to start the demo.',
    problemTitle: 'Saturday evening. They like your product. The shop is closed.',
    today: 'TODAY', withQr2buy: 'WITH QR2BUY',
    problemBefore: ['They like the product.', 'The shop is closed.', 'They walk on.'],
    problemAfter: ['Scan the QR.', 'Pay or reserve.', 'Sold or reserved.'],
    benefitsTitle: 'Turn interest into a buying moment.', benefitsText: 'Right beside the visible product.',
    benefits: [['No app', 'Open the camera and go.'], ['After closing too', 'Buy or reserve when the product catches your eye.'], ['Visible confirmation', 'The display shows the confirmed action.']],
    compareQr2buyText: 'This exact product. Price and availability. Buy or reserve.',
    compareStandardItems: ['Opens a website', 'Does not automatically identify the product', 'Display stays static'],
    compareQr2buyItems: ['Opens this exact product', 'Shows price and availability', 'Buy or reserve on your phone', 'Display reacts to the confirmed action'],
    trustTitle: 'You know what you are buying.', trustText: 'Product, price and confirmed feedback on phone and display.',
    trustItems: ['The exact product in front of you', 'Price and availability before purchase', 'Payment with Stripe – currently test mode only', 'Email confirmation in the accepted merchant test purchase'],
    cases: [['Boutique', 'Favourite pieces in the window.'], ['Gallery', 'Art right in front of you.'], ['Showroom', 'Discover displayed products.'], ['Seasonal stand', 'Visible products, even without staff on site.']],
    casesText: 'And anywhere products are visible while nobody is there to sell.',
    howSteps: [['1', 'See the product', 'Name, price and QR beside the product.'], ['2', 'Scan the QR', 'Camera and browser are enough.'], ['3', 'Buy or reserve', 'The display shows the confirmed action.']],
    hardwareTitle: 'A price tag that can sell.',
    hardwareText: 'Two real displays have passed MVP acceptance. Working prototypes; enclosure and final product design follow in the pilot.',
    hardwareFacts: ['Product', 'Price', 'QR and availability', 'Live reaction', 'Reusable'],
    pilotTitle: 'Try QR2BUY in your own shop window.', pilotText: 'We plan a focused pilot with your visible products.',
    faq: [['Can I register as a merchant?', 'Yes. The merchant portal is available. We agree display provisioning and pilot scope together.'], ['Can I accept real payments?', 'Not yet. Merchant checkout has passed test-mode acceptance; live payments and payouts are not enabled.'], ['Does the demo create a real order?', 'No. Test data and Stripe test mode only, no charge or real order.'], ['Do real displays exist?', 'Yes. Two physical prototypes have passed acceptance with one real merchant.'], ['Do customers need an app?', 'No. A camera and browser are enough.'], ['What does a pilot cost?', 'We plan the scope and price together.']],
  },
};
