// The live merchant product and the optional commerce demo are separate flows.
export const pilotCopy = {
  de: {
    merchantStart: 'Als Händler starten', merchantLogin: 'Händler-Login',
    merchantTitle: 'Bereit für dein eigenes Verkaufsschild?',
    merchantIntro: 'Registriere dein Geschäft, lege Produkte und Preise an und verbinde deine qr2buy-Verkaufsschilder direkt vor Ort. Schilder werden im Rahmen des Piloten bereitgestellt.',
    merchantScope: 'Heute verfügbar: Händlerportal, Standorte, Produkte, Preis und Bestand, Vor-Ort-Binding und öffentliche Produktseiten – live mit deinen Schildern synchronisiert.',
    commerceScope: 'Verfügbare Angebote können reserviert werden, wenn der Händler dies erlaubt. Online-Kauf und Auszahlungen sind noch nicht verfügbar. Den Kaufablauf kannst du separat in der Demo mit Testdaten ausprobieren.',
    hero: 'Deine Produkte sichtbar. Deine Preise aktuell. Auch nach Ladenschluss.',
    heroText: 'Mit qr2buy verbinden Händler reale Verkaufsschilder mit ihren Produkten. Kunden scannen den QR-Code und sehen Preis und Verfügbarkeit direkt am Handy – ohne App.',
    heroTrust: 'Händlerportal und echte Schilder sind live. Echte Reservierungen sind bei freigegebenen Angeboten möglich. Den Kauf zeigen wir in der separaten Demo.',
    problemText: 'Samstagabend. Jemand entdeckt dein Produkt im Schaufenster. Mit qr2buy findet er Preis und Verfügbarkeit direkt am Handy – auch bei geschlossener Tür.',
    benefitsTitle: 'Ein Verkaufsschild, das mit deinem Geschäft Schritt hält.',
    benefitsText: 'Pflege Produkte, Preise und Bestand im Händlerportal. Deine Schilder und die öffentlichen Produktseiten zeigen den aktuellen Stand.',
    benefits: [['Keine App', 'Die Smartphone-Kamera öffnet die Produktseite.'], ['Aktuelle Preise', 'Änderungen werden auf deinen Schildern sichtbar.'], ['Bestand im Blick', 'Ausverkaufte und wieder verfügbare Produkte reagieren auf deinen Bestand.'], ['Vor Ort verbinden', 'Bestätige die Produktzuordnung direkt am echten Schild.']],
    compareQr2buyText: 'Verbindet Produkt, Preis, Verfügbarkeit und das physische Verkaufsschild.',
    trustTitle: 'Dasselbe Produkt. Derselbe Preis. Auf Schild und Smartphone.',
    trustText: 'Das Händlerportal steuert Preis und Bestand. Deine Kunden sehen die aktuelle öffentliche Produktseite nach dem QR-Scan.',
    trustItems: ['Derselbe Produktname auf Schild und Smartphone', 'Preis und aktuelle Verfügbarkeit sichtbar', 'Zuordnung vor Ort am Schild bestätigt', 'Kaufablauf separat im Testmodus erlebbar'],
    cases: [['Mode & Accessoires', 'Produkte im Schaufenster mit aktuellen Informationen zeigen.'], ['Kunst & Galerie', 'Originale und limitierte Arbeiten sichtbar machen.'], ['Design & Einrichtung', 'Ausstellungsstücke und Preise im Showroom verbinden.'], ['Fahrräder', 'Modelle und Verfügbarkeit auch nach Ladenschluss zeigen.'], ['Pflanzen', 'Preise und Bestand einfach aktuell halten.'], ['Hochwertige Einzelstücke', 'Identität, Preis und Status sichtbar halten.'], ['Showrooms', 'Produktinformationen ohne permanente Betreuung bereitstellen.']],
    howSteps: [['1', 'Geschäft einrichten', 'Als Händler registrieren, Standort und Produkte anlegen.'], ['2', 'Schild verbinden', 'Das Produkt vor Ort mit deinem bereitgestellten Schild verbinden.'], ['3', 'Produkt ansehen', 'Kunden scannen den QR-Code zur öffentlichen Produktseite.'], ['4', 'Aktuell bleiben', 'Preis- und Bestandsänderungen erreichen Schild und Produktseite.']],
    hardwareText: 'Zwei reale Verkaufsschilder sind im Händlerbetrieb abgenommen. Produkt, Preis und Bestand werden synchronisiert; der Buyer-QR öffnet die öffentliche Produktseite.',
    hardwareFacts: ['Echtes Farbdisplay', 'Live mit dem Händlerportal verbunden', 'Produktwechsel vor Ort bestätigt', 'QR real scanbar', 'Preis und Bestand synchronisiert'],
    pilotTitle: 'Teste qr2buy an deinem Verkaufsort.',
    faq: [['Kann ich mich schon als Händler registrieren?', 'Ja. Geschäft, Standorte, Produkte, Angebote und Schilderverwaltung sind live. Die Bereitstellung der Schilder stimmen wir im Pilotprojekt ab.'], ['Kann ich schon echte Zahlungen empfangen?', 'Nein. Händler-Checkout, Stripe Connect und Auszahlungen sind noch nicht verfügbar.'], ['Ist die Demo eine echte Bestellung?', 'Nein. Die separate Marketing-Demo nutzt ausschließlich Testdaten und die Stripe-Sandbox. Sie erzeugt keine echte Bestellung.'], ['Gibt es die Schilder als Hardware?', 'Ja. Der Händlerfluss mit zwei echten Schildern, Preis- und Bestandsänderungen und Buyer-QR ist manuell abgenommen.'], ['Brauchen Kunden eine App?', 'Nein. Kamera und Browser reichen für die öffentliche Produktseite.'], ['Was kostet der Pilot?', 'Umfang und Preis planen wir gemeinsam für deinen Verkaufsort.']],
  },
  en: {
    merchantStart: 'Get started as a merchant', merchantLogin: 'Merchant login',
    merchantTitle: 'Ready for your own sales display?',
    merchantIntro: 'Register your business, add products and prices, and connect your qr2buy displays on site. Displays are provided as part of the pilot.',
    merchantScope: 'Available today: merchant portal, locations, products, price and stock, on-site binding and public product pages – synchronized live with your displays.',
    commerceScope: 'Available offers can be reserved when enabled by the merchant. Online checkout and payouts are not yet available. Explore the purchase journey separately in the demo using test data.',
    hero: 'Your products visible. Your prices current. Even after closing time.',
    heroText: 'qr2buy connects real sales displays to your products. Customers scan the QR code to see price and availability on their phone – no app required.',
    heroTrust: 'The merchant portal and real displays are live. Real reservations are available for enabled offers. Buying remains in the separate demo.',
    problemText: 'Saturday evening. Someone spots your product in the window. With qr2buy they can see its price and availability on their phone, even while the shop is closed.',
    benefitsTitle: 'A sales display that keeps up with your business.',
    benefitsText: 'Manage products, prices and stock in the merchant portal. Your displays and public product pages show the current information.',
    benefits: [['No app', 'The phone camera opens the product page.'], ['Current prices', 'Changes appear on your displays.'], ['Stock in view', 'Sold-out and available products reflect your inventory.'], ['Connect on site', 'Confirm the product on the real display.']],
    compareQr2buyText: 'Connects the product, price, availability and physical display.',
    trustTitle: 'The same product. The same price. On display and phone.',
    trustText: 'The merchant portal controls price and stock. Customers see the current public product page after scanning the QR code.',
    trustItems: ['Same product name on display and phone', 'Current price and availability', 'Product binding confirmed on site', 'Separate demo for the test purchase journey'],
    cases: [['Fashion & accessories', 'Show current product information in the window.'], ['Art & galleries', 'Make originals and limited editions visible.'], ['Design & interiors', 'Connect showroom products and prices.'], ['Bicycles', 'Show models and availability after closing time.'], ['Plants', 'Keep prices and stock up to date.'], ['Unique items', 'Keep identity, price and status visible.'], ['Showrooms', 'Provide product information without constant supervision.']],
    howSteps: [['1', 'Set up your business', 'Register and add your locations and products.'], ['2', 'Connect a display', 'Bind the product to your provided display on site.'], ['3', 'View the product', 'Customers scan the QR code to open its public page.'], ['4', 'Stay up to date', 'Price and stock changes reach displays and product pages.']],
    hardwareText: 'The merchant flow has been accepted on two real displays. Product, price and stock are synchronized; the buyer QR opens the public product page.',
    hardwareFacts: ['Real color display', 'Connected live to the merchant portal', 'Product changes confirmed on site', 'Scannable QR', 'Price and stock synchronized'],
    pilotTitle: 'Try qr2buy at your point of sale.',
    faq: [['Can I register as a merchant now?', 'Yes. Businesses, locations, products, offers and display management are live. We arrange display provisioning within the pilot.'], ['Can I accept real payments?', 'No. Merchant checkout, Stripe Connect and payouts are not available yet.'], ['Does the demo create a real order?', 'No. The separate marketing demo uses test data and the Stripe Sandbox. It creates no real order.'], ['Do physical displays exist?', 'Yes. The merchant flow on two real displays, price and stock changes and buyer QR have passed manual acceptance.'], ['Do customers need an app?', 'No. A camera and browser are enough for the public product page.'], ['What does a pilot cost?', 'We plan the scope and price together for your location.']],
  },
};
